print("HI hi Hi HA HA hA")
print("SAJjan")
print("asjkfghasdjkf sjkghfdjsghhfdgkjs j jsffhgkjshfdghdskjd hfdshgjkhfdskj ghjdfkgh kjsh gjksdhfjkghuhgiufhgiuhsdfjkgh kjsgiudhiguhfdkjg jkerrgiusergiuaeigbqerjghuioegkjdfgioerrgbadslkbvmdffo igjrrieogiujedrhg ikuerdgdflh bodf")
print("Sajjan Boy buddy")
print("HIHIHIHIHIHIHIHIHIHIHIHIHIHIHI")
